/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlausableIndexRouteImport } from './routes/plausable.index'
import { Route as CoolifyIndexRouteImport } from './routes/coolify.index'
import { Route as CoolifyCoolifyIdRouteImport } from './routes/coolify.$coolifyId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlausableIndexRoute = PlausableIndexRouteImport.update({
  id: '/plausable/',
  path: '/plausable/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoolifyIndexRoute = CoolifyIndexRouteImport.update({
  id: '/coolify/',
  path: '/coolify/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoolifyCoolifyIdRoute = CoolifyCoolifyIdRouteImport.update({
  id: '/coolify/$coolifyId',
  path: '/coolify/$coolifyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/coolify/$coolifyId': typeof CoolifyCoolifyIdRoute
  '/coolify': typeof CoolifyIndexRoute
  '/plausable': typeof PlausableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/coolify/$coolifyId': typeof CoolifyCoolifyIdRoute
  '/coolify': typeof CoolifyIndexRoute
  '/plausable': typeof PlausableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/coolify/$coolifyId': typeof CoolifyCoolifyIdRoute
  '/coolify/': typeof CoolifyIndexRoute
  '/plausable/': typeof PlausableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/coolify/$coolifyId'
    | '/coolify'
    | '/plausable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/coolify/$coolifyId' | '/coolify' | '/plausable'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/coolify/$coolifyId'
    | '/coolify/'
    | '/plausable/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CoolifyCoolifyIdRoute: typeof CoolifyCoolifyIdRoute
  CoolifyIndexRoute: typeof CoolifyIndexRoute
  PlausableIndexRoute: typeof PlausableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plausable/': {
      id: '/plausable/'
      path: '/plausable'
      fullPath: '/plausable'
      preLoaderRoute: typeof PlausableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coolify/': {
      id: '/coolify/'
      path: '/coolify'
      fullPath: '/coolify'
      preLoaderRoute: typeof CoolifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coolify/$coolifyId': {
      id: '/coolify/$coolifyId'
      path: '/coolify/$coolifyId'
      fullPath: '/coolify/$coolifyId'
      preLoaderRoute: typeof CoolifyCoolifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CoolifyCoolifyIdRoute: CoolifyCoolifyIdRoute,
  CoolifyIndexRoute: CoolifyIndexRoute,
  PlausableIndexRoute: PlausableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
